/**~interaction~
 * MessageSort [Enumeration]
 * 
 * Description
 * 
 * This is an enumerated type that identifies the type of communication action that was used to generate the Message.
 * 
 * Diagrams
 * 
 *  Messages
 * 
 * Literals
 * 
 *  synchCall
 * 
 * The message was generated by a synchronous call to an operation.
 * 
 *  asynchCall
 * 
 * The message was generated by an asynchronous call to an operation; i.e., a CallAction with isSynchronous =
 * false.
 * 
 *  asynchSignal
 * 
 * The message was generated by an asynchronous send action.
 * 
 *  createMessage
 * 
 * The message designating the creation of another lifeline object.
 * 
 *  deleteMessage
 * 
 * The message designating the termination of another lifeline.
 * 
 *  reply
 * 
 * The message is a reply message to an operation call.
**/